services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=denopass
      - POSTGRES_USER=denobot
      - POSTGRES_DB=denobot
    ports:
      - "5432:5432"

volumes:
  postgres-data:
