name: Deno Test and Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-check:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno tests
        run: deno test --allow-all

      - name: Run Deno lint and format check
        run: |
          deno lint
          deno fmt --check
